/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 public/models/opti.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Dog(props) {
  const { nodes, materials } = useGLTF('./models/opti.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.lowPoly.geometry} material={materials['gun dog opti']} position={[0, 0, 0]} rotation={[-1.57, -0.001, 1.929]} scale={0.1} />
    </group>
  )
}

useGLTF.preload('./models/opti.gltf')
