/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 public/models/lp.glb
*/

import { useGLTF, PerspectiveCamera, useScroll } from '@react-three/drei'
import gsap from "gsap";
import { useLayoutEffect, useRef } from 'react';
import { useFrame } from '@react-three/fiber';

export const FLOOR_HEIGHT = 3;
export const NB_FLOORS = 2;

export function Earth(props) {
  const { nodes, materials } = useGLTF('./models/lp.glb')
  const ref = useRef();
  const tl = useRef();

  const scroll = useScroll();



  useFrame (() => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });


  useLayoutEffect (() => {
    tl.current = gsap.timeline();

    //ROTATION
    tl.current.from(
      ref.current.rotation,
      {
        duration: 2,
        y: -3,
      },
      0
    )

    //VERTICAL ANIMATION
    tl.current.to(
      ref.current.position,
      {
        duration: 0.5,
        x: -FLOOR_HEIGHT * (NB_FLOORS - 1),
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1) / 3,

      },
      0.5
    ); 

  }, []);


  return (
    <group {...props} dispose={null} ref={ref}>
      <group rotation={[-1.569, -0.001, 2.269]} position={[0, 0, 0]} scale={1}>
        <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Sphere002_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Sphere002_2.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Sphere002_3.geometry} material={materials['Material.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/lp.glb')



