/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 public/models/lp.glb
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Lp(props) {
  const { nodes, materials } = useGLTF('./models/lp.glb')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={100000} near={10} fov={39.598} position={[-376.412, 212.606, -393.106]} rotation={[0.015, -0.815, -0.354]} scale={10} />
      <group rotation={[-1.569, -0.001, 2.269]} scale={1}>
        <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Sphere002_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Sphere002_2.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Sphere002_3.geometry} material={materials['Material.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/lp.glb')
