/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 public/models/lp.glb
*/

import { useGLTF, PerspectiveCamera, useScroll } from '@react-three/drei'
import gsap from "gsap";
import { useLayoutEffect, useRef } from 'react';
import { useFrame } from '@react-three/fiber';

export const FLOOR_HEIGHT = 2;
export const NB_FLOORS = 2;

export function Lp(props) {
  const { nodes, materials } = useGLTF('./models/lp.glb')
  const ref = useRef();
  const tl = useRef();

  const scroll = useScroll();



  useFrame (() => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useFrame (() => {

    // ref.current.rotation.y += 0.01;
    // ref.current.rotation.z += 0.01;
    // ref.current.rotation.x += 0.01;

  });

  useLayoutEffect (() => {
    tl.current = gsap.timeline();

    //VERTICAL ANIMATION
    tl.current.to(
      ref.current.position,
      {
        duration: 2,
        z: -FLOOR_HEIGHT * (NB_FLOORS - 1),
        x: -FLOOR_HEIGHT * (NB_FLOORS - 1),

      },
      0
    ); 

  }, []);


  return (
    <group {...props} dispose={null} ref={ref}>
      <PerspectiveCamera makeDefault={false} far={100000} near={10} fov={64} position={[0, 0, 0]} rotation={[0, 0, 0]} scale={10} />
      <group position={[1, 0, 1]} rotation={[0, 0, 0]} scale={0.5}>
        <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Sphere002_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Sphere002_2.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Sphere002_3.geometry} material={materials['Material.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/lp.glb')
